"""Background deployment task — deploys to Sepolia testnet."""
import sys, os, json, time
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from datetime import datetime
from web3 import Web3
from app.database import SessionLocal
from app.models import Asset, GeneratedContract, Deployment, AuditEvent
from app.config import get_settings

settings = get_settings()

# Pre-compiled bytecode for TzeroSecurityToken (compiled from our Solidity template)
# This is generated by running: cd contracts && npx hardhat compile
# We embed it here so deployment works without Hardhat at runtime
COMPILED_BYTECODE_PATH = os.path.join(
    os.path.dirname(__file__), "..", "..", "contracts", "artifacts",
    "contracts", "TzeroSecurityToken.sol", "TzeroSecurityToken.json"
)

TOKEN_ABI = [
    {"inputs": [{"name": "_name","type": "string"},{"name": "_symbol","type": "string"},
                {"name": "_preMoneyValuation","type": "uint256"},{"name": "_lockUpMonths","type": "uint256"},
                {"name": "_requiresAccredited","type": "bool"},{"name": "_owner","type": "address"}],
     "stateMutability": "nonpayable","type": "constructor"},
    {"inputs": [{"name": "account","type": "address"}],"name": "whitelist","outputs": [],"stateMutability": "nonpayable","type": "function"},
    {"inputs": [{"name": "to","type": "address"},{"name": "amount","type": "uint256"}],"name": "mint","outputs": [],"stateMutability": "nonpayable","type": "function"},
    {"inputs": [],"name": "lockUpEnd","outputs": [{"name": "","type": "uint256"}],"stateMutability": "view","type": "function"},
    {"inputs": [],"name": "preMoneyValuation","outputs": [{"name": "","type": "uint256"}],"stateMutability": "view","type": "function"},
    {"inputs": [],"name": "name","outputs": [{"name": "","type": "string"}],"stateMutability": "view","type": "function"},
    {"inputs": [],"name": "symbol","outputs": [{"name": "","type": "string"}],"stateMutability": "view","type": "function"},
    {"inputs": [],"name": "totalSupply","outputs": [{"name": "","type": "uint256"}],"stateMutability": "view","type": "function"},
]


def _load_bytecode() -> str:
    if os.path.exists(COMPILED_BYTECODE_PATH):
        with open(COMPILED_BYTECODE_PATH) as f:
            artifact = json.load(f)
            return artifact.get("bytecode", "")
    return ""


def run_deployment(asset_id: str):
    db = SessionLocal()
    try:
        asset = db.query(Asset).filter(Asset.id == asset_id).first()
        if not asset:
            return

        contract_rec = (db.query(GeneratedContract)
                        .filter(GeneratedContract.asset_id == asset_id)
                        .order_by(GeneratedContract.generated_at.desc()).first())
        if not contract_rec:
            return

        params = contract_rec.parameter_snapshot or {}

        deployment = Deployment(
            asset_id=asset_id,
            contract_id=contract_rec.id,
            network="sepolia",
            status="pending",
        )
        db.add(deployment)
        db.commit()
        db.refresh(deployment)

        # Connect to Sepolia
        w3 = Web3(Web3.HTTPProvider(settings.sepolia_rpc_url))
        if not w3.is_connected():
            raise ConnectionError("Cannot connect to Sepolia RPC")

        account = w3.eth.account.from_key(settings.deployer_private_key)

        bytecode = _load_bytecode()
        if not bytecode:
            raise FileNotFoundError(
                "Contract bytecode not found. Run: cd contracts && npm install && npx hardhat compile"
            )

        # Build constructor args
        token_name = str(params.get("asset_name", "Tzero Asset Token"))
        token_symbol = str(params.get("token_symbol", "TZT"))[:5]
        pre_money = int(params.get("pre_money_valuation_cents", 0))
        lock_up = int(params.get("lock_up_months", 12))
        requires_accredited = str(params.get("requires_accredited", "true")).lower() == "true"
        owner = account.address

        ContractFactory = w3.eth.contract(abi=TOKEN_ABI, bytecode=bytecode)

        nonce = w3.eth.get_transaction_count(account.address)
        gas_price = w3.eth.gas_price

        tx = ContractFactory.constructor(
            token_name, token_symbol, pre_money, lock_up, requires_accredited, owner
        ).build_transaction({
            "from": account.address,
            "nonce": nonce,
            "gas": 2_000_000,
            "gasPrice": gas_price,
        })

        signed = account.sign_transaction(tx)
        tx_hash = w3.eth.send_raw_transaction(signed.raw_transaction)
        tx_hash_hex = tx_hash.hex()

        deployment.tx_hash = tx_hash_hex
        deployment.status = "pending"
        db.commit()

        # Update asset with tx_hash so UI shows it immediately
        asset.status = "deploying"
        asset.updated_at = datetime.utcnow()
        db.commit()

        # Wait for confirmation (up to 3 minutes)
        receipt = None
        for attempt in range(36):  # 36 × 5s = 3 min
            time.sleep(5)
            try:
                receipt = w3.eth.get_transaction_receipt(tx_hash)
                if receipt:
                    break
            except Exception:
                continue

        if receipt and receipt.status == 1:
            deployment.contract_address = receipt.contractAddress
            deployment.block_number = receipt.blockNumber
            deployment.gas_used = receipt.gasUsed
            deployment.status = "confirmed"
            deployment.confirmed_at = datetime.utcnow()
            asset.status = "deployed"
        else:
            deployment.status = "failed"
            deployment.error_message = "Transaction failed or timed out"
            deployment.attempt_count += 1
            asset.status = "contract_approved"  # allow retry

        asset.updated_at = datetime.utcnow()
        db.add(AuditEvent(
            asset_id=asset_id,
            actor_id=None,
            event_type="deployment_" + deployment.status,
            payload={
                "tx_hash": tx_hash_hex,
                "contract_address": deployment.contract_address,
                "network": "sepolia",
            },
        ))
        db.commit()

    except Exception as e:
        db.rollback()
        try:
            dep = (db.query(Deployment)
                   .filter(Deployment.asset_id == asset_id)
                   .order_by(Deployment.deployed_at.desc()).first())
            if dep:
                dep.status = "failed"
                dep.error_message = str(e)
            asset = db.query(Asset).filter(Asset.id == asset_id).first()
            if asset:
                asset.status = "contract_approved"
                asset.updated_at = datetime.utcnow()
            db.add(AuditEvent(
                asset_id=asset_id,
                actor_id=None,
                event_type="deployment_failed",
                payload={"error": str(e)},
            ))
            db.commit()
        except Exception:
            pass
    finally:
        db.close()
